version: '2'
services:
  adminjhipster-app:
    image: adminjhipster
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://adminjhipster-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=adminJhipster
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  adminjhipster-mongodb:
    extends:
      file: mongodb.yml
      service: adminjhipster-mongodb
